---
title: "Personligt Brev"
author: "Erik Marsja"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: pdflatex
    template: template.tex
  html_document:
    df_print: paged
  word_document: default
email: erik.marsja@liu.se
fontawesome: yes
geometry: margin=1in
github: marsja
lang: Swedish, English
phone: +4670-3633662
subparagraph: yes
address: Tvistevägen 26, SE-907 36 Umeå, Sweden
web: www.marsja.se
cletter: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Till den det berör,

\
Jag vill uttrycka mitt intresse för positionen som biträdande lektor i funktionsnedsättning och samhälle vid institutionen för beteendevetenskap och lärande, Linköpings universitet. För tillfället arbetar jag som postdoktor vid avdelningen för funktionsnedsättning och samhälle, institutionen för beteendevetenskap och lärande, Linköpings Universitet och som forskare vid människan i transportsystemet, Statens Väg- och Transportforskningsinstitut (VTI). Att forska och undervisa inom funktionsnedsättning och samhälle finner jag väldigt intressant och stimulerande. Detta framför allt eftersom jag det ger mig ett tillfälle att tillämpa de färdigheter jag anförskaffat mig som doktorand och postdoktor, inklusive mina starka färdigheter i forskning, avancerad statistik, och metod. Sedan min forskarutbildning har jag brunnit för öppen vetenskap (var exv. med vid grundadet av Open Science Community Sweden) och har som målsättning att för-registrera mina egna projekt, laddar upp analysskript och data för mina studier när det är möjligt, och strävar således efter både öppen- såväl som reproducerbarhet. Generellt sett har min forskning fokuserat på multisensorisk perception och uppmärksamhet, kognitiva och psykosociala aspekter av hörselnedsättning. Det vill säga, min forskning tillika planerad forskning innefattar ett spann av metoder inom funktionsnedsättning och samhälle, psykologi samt kognitionsvetenskap. Forskningsmässigt strävar jag efter att bidra till både teori i form av grundforskning men även att i andra projekt kunna bidra mer direkt med tillämpad kunskap.

\
Mina undervisningserfarenheter inkluderar både kvantitativ och kvalitativ forskningsmetod, tillämpad kognitiv psykologi, kognitionspsykologi, neurovetenskap, och handikappvetenskap (numer benämnt som funktionsnedsättning och samhälle). Jag har varit involverad i handledning av projekt där studenter, tillsammans med företag, utför projekt där de ska tillämpa grundforskning (exv. arbetat utifrån den biopsykosociala modellen). Dessa projekt, inklusive uppsatshandledning, har innefattat flera områden inom psykologi, människo-datorinteraktion, kognitions- och handikappvetenskap. Vidare har jag deltagit i flera internationella konferenser, undervisat för internationella studenter, och samarbetat med internationella forskare. 

På min fritid tycker jag om att läsa, laga mat, och baka surdegsbröd. Jag tycker även om att fjällvandra, jogga, odla och spendera tid med min familj och vänner. De senaste åren har jag även fattat tycke för att fiska. Ibland så skriver jag på min Python och R-programmeringsblogg. Är något av en kaffenörd.

\
Jag ser fram emot att växa i en intellektuellt utmanande miljö och att arbeta med min forskning tillika med undervisning inom funktionsnedsättning och samhälle, psykologi och kognitionsvetenskap. Slutligen, är jag övertygad om att min erfarenhet och mina meriter skulle vara av stort gagn för både avdelningen för funktionsnedsättning och samhälle och Linköpings universitet. 

\
Tveka inte att ta kontakt med mig via 0703633662 eller erik.marsja@liu.se. Tack för ert övervägande och er tid.

\
Med Vänlig Hälsning,

\
Dr Erik Marsja
