---
title: "Konferensdeltagande och refereeuppdrag"
author: "Erik Marsja"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: pdflatex
    template: template.tex
  html_document:
    df_print: paged
  word_document: default
email: erik.marsja@liu.se
fontawesome: yes
geometry: margin=1in
github: marsja
lang: Swedish, English
phone: +4670-36 33 662
subparagraph: yes
address: Tvistevägen 26, SE-907 36 Umeå, Sweden
web: www.marsja.se
CV: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Deltog aktivt i workshops, träffade seniora forskare och lyssnade på föreläsningar på Society of Improving Psychological Science årliga möte 2019, Rotterdam, Nederländerna. Detta möte har ett fokus på att förbättra Psykologisk forskning och innefattar t.ex. avancerad statistisk metod, öppen vetenskap, reproducerbarhet, och annat närliggande. Nationellt deltog jag i en minkonferens med efterföljande möte som ledde till att Open Science Community Sweden grundades 2019 (https://opensciencesweden.org/).

## Nationella och Internationella konferensbidrag

Totalt: 12

### Muntliga presentationer

  1. **Marsja**, E., Marsh, J.E., Neely G., Hansson P., Ljungberg K.J., (2016, June). Spatial Change in Multisensory Distractors Impact on Verbal and Spatial Short Term Memory. International Multisensory Research Forum 17^th^ annual meeting, Suzhou, CHN.

### Posterpresentationer

Totalt: 9

  1. **Marsja**, E., Danielsson, H., Stenbäck, V., Moradi, S., Rönnberg, J. (2019, November). Examining how Cognitive Functioning, Aging, and Hearing Loss, Affect Speech-in-Noise Performance. Aging and Speech Communication conference, Tampa, Florida, USA. 

  2. Stenbäck, V., **Marsja**, E., Danielsson, H., Rönnberg, J. (2019, November). Logical and Auditory Inference Making: Performance in the HINT in normally-hearing and hearing-impaired listeners. Aging and Speech Communication conference, Tampa, Florida, USA. 

  3. Bampouni, E., **Marsja**, E., Sörman, D.E., & Ljungberg, K.J (2019, November). Do Action Gamers Have Enhanced Visual Search Skills? a Realistic Task Approach. The 15th SweCog conference of the Swedish Cognitive Science Society, Umeå, Sweden.  

  4. **Marsja**, E., Danielsson, H., Stenbäck, V., Moradi, S., & Rönnberg, J. (2019, June). Examining Relationship Amongst Cognition, Hearing Loss, Age, & Speech in Noise. Cognitive Hearing Science for Communication, Linköping, Sweden. 

 5. Stenbäck, V., Moradi, S., **Marsja**, E., Danielsson, H., & Rönnberg, J. (2019, June). Logical and auditory inference-making in normally-hearing and hearing-impaired listeners. Cognitive Hearing Science for Communication, Linköping, Sweden. 

 6. **Marsja**, E., Neely G., Ma, L., Ljungberg K.J., (2015, August). Cross-modality matches of intensity and attention capture dimensions of auditory and vibrotactile stimuli. Fechner Day 2015. The 31^st^ Annual Meeting of the International Society for Psychophysics, Québec, CA. 

 7. **Marsja**, E., Neely, G., Parmentier, F.B.R., Ljungberg, K.J., (2014, October) Deviance Distraction Is Contingent on Stimuli Being Presented within the Same Modality. Psychonomic Society’s 55^th^ Annual Meeting. Long Beach, CA, USA. 

 8. Ljungberg, K.J., Parmentier, F.B.R., **Marsja**, E., Neely, G., Jones, D., (2014, January). Any Tom, Dick, or Harry will do: Hearing one’s own name distracts no more than any other in a cross-modal oddball task. Experimental Psychology Society Meeting. London, UK. 

 9. **Marsja**, E., Neely, G., Parmentier, F.B.R., Ljungberg, K.J., (2013, October). Maintenance of the distractive effect of deviating vibrotactile stimuli in a cross-modal oddball paradigm.  The 29^th^ Annual meeting of the International Society of Psychophysics, Freiburg, DE. 


### Inbjudna Föredrag

 1. **Marsja**, E., Marsh, J.E., Neely G., Hansson P., Ljungberg K.J., (2016, September). Do Spatial Changes in Sounds and Vibrations Affect Visuo-spatial and Verbal Short-Term Memory? Attention and Control: Insights from Distraction, Workshop, University of Central Lancashire, Preston, UK. 

## Andra Föredrag

 1. **Marsja**, E., Marsh, J.E., Neely G., Hansson P., Ljungberg K.J., (2017, April). Domain-generality or domain-specificity of the short-term memory: insights from a multisensory distraction paradigm. Re-thinking the Senses Spring School, Dubrovnik, Croatia. *Poster med kort "pitch talk"*.

## Refereegranskat för tidskrifter:

* Journal of Cognitive Psychology
* Frontiers of Psychology
* Behavior Research Methods

Genomsnittligt ett uppdrag per år.


