---
title: "Nuvarande och Planerad Forskning"
author: "Erik Marsja"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: pdflatex
    template: template.tex
  html_document:
    df_print: paged
  word_document: default
email: erik.marsja@liu.se
fontawesome: yes
geometry: margin=1.2in
github: marsja
language: Swedish, English
phone: 0046703633662
subparagraph: yes
address: Tvistevägen 26, SE-907 36 Umeå, Sweden
web: www.marsja.se
vetenskap: TRUE
swedish: TRUE
dob: 19810526
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tidigare och Nuvarande Forskning
Min tidigare och nuvarande forskning har undersökt hur stimuli i bakgrunden (exv. irrelevanta ljud eller vibrationer) påverkar mänsklig perception. Från min kandidatuppsats, och fram till min doktorsavhandling, studerade jag hur plötsliga förändringar, och irrelevanta, i omgivningen fångar uppmärksamheten från en primär uppgift. Under min tid som postdoktor har min forskning breddats till att även innefatta funktionsnedsättning (än så länge hörselnedsättning), kognitiv funktion, åldrande, och identifikationen av tal i bakgrundsbrus och tal. Se följande två underrubriker för en mer detaljerad beskrivning av min tidigare och nuvarande forskning.

### Multisensorisk perception och uppmärksamhet
I min kandidatuppdats undersökte jag huruvida det egna namnet har en särskild förmåga att fånga uppmärksamhet i jämfört med ett annat, familjärt, namn. Med detta experiment visade jag att så är inte fallet när vi applicerar en gedigen experimentell kontroll (exv. matchar antal stavelser i namnen). Vi följde sedan upp detta med ett experiment där vi använda ord på vanliga objekt (exv. stol, och bord) och, återigen, så visade vi att en persons eget namn har inte förmågan att fånga uppmärksamheten mer än andra ord (Ljungberg et al., 2014). Dessa resultat antyder att det finns begränsningar i de kognitiva teorier som föreslagit att en persons egna namn exv. bryter igenom uppmärksamhetsfiltret lättare än andra ord (e.g., Cherry, 1952).

I min doktorsavhandling (Marsja, 2017) undersökte jag hur irrelevanta oväntade hörsel- och taktila stimuli har inverkan på visuell bearbetning. I de två första studierna av min avhandling använde jag enkla visuella kategoriseringsuppgifter och dessa två studier identifierade en kunskapslucka som leder till den tredje studien: Hur påverkar plötsliga förändringar i irrelevanta auditiva, taktila eller bimodala (både taktila och auditiva) sekvenser korttidsminnesprocesser?

Resultaten visade att distraktion av plötsliga, och oväntade, vibration liknar distraktion som uppstår när plötsliga ljud presenteras (cf. Fabrice, 2014). Vidare fann jag att en möjlig skillnad är att effekten av oväntade vibrationer försvinner över tid (Marsja, Neely, K-Ljungberg, In Preparation). I den andra studien i avhandlingen fann jag att ljud som presenteras bland upprepade vibrationer bara är distraherande när vibrationen inte presenteras samtidigt som ljudet. Att utelämna en upprepad vibration räcker för att fånga uppmärksamheten (Marsja, Neely, K-Ljungberg, 2018). När det gäller bearbetning av information i korttidsminnet visade resultaten att en plötslig förändring av spatial lokalisation i irrelevant sekvens stör korttidsminnesprocesser när den irrelevanta sekvensen består av både ljud och vibrationer (Marsja, Marsh, Hansson, & Neely, 2019). 

Tillsammans med internationella och nationella forskare inom kognitionspyskologi genomförde jag en serie om 3 experiment. Syftet med dessa experiment var att undersöka vad som stör det visuella korttidsminnet (Marsh, et al., In Preparation). I den här studien använde vi vibrotaktila sekvenser med en konstant förändring (sekvensen "hoppar" mellan de två händerna, vänster-höger-vänster-höger-vänster-höger; *changing-state* sekvens), och *steady-state* sekvenser (när alla vibrationer i sekvensen presenteras till båda händerna). Vi fann att visuellt korttidsminnes prestanda störs mer av en vibrotaktil sekvens i växlande tillstånd jämfört med en taktil sekvens i stabilt tillstånd. Effekten av en vibrotaktil sekvens i växlande tillstånd liknar dessutom den av sekvensen i växlande tillstånd som består av ljud (experiment 1); interferensen mellan vibrotaktila stimuli och korttidsminne tycks påverka återkallandet av objekts ordning i korttidsminnet (experiment 2), och förutsägbarheten av vibrotaktila stimuli verkar inte påverka omfattningen av effekten (experiment 3). Studierna i min avhandling och den tillsammans med Marsh et al. (In Preparation) sammanfaller med tidigare forskning (e.g., fann denna avhandling att både plötsliga och oväntade förändringar i auditiva och taktila irrelevanta sekvenser fångar uppmärksamhet från en visuell uppgift. Men den temporala dynamiken mellan de två modaliteterna verkar skilja sig. Det verkar som att upprepad utsättning för plötsliga och oväntade vibrationer gör att den negativa effekten minskar, medan detta inte är fallet i den auditiva modaliteten. Detta tyder på att det finns centrala mekanismer (upptäckt av en plötsligförändring) och sensorikspecifika mekanismer.

Vidare har vi studerat interaktionen mellan de auditiva, visuella och taktila modaliteterna från ett tillämpat perspektiv. I en studie syftade vi till att fastställa hur effektiv en taktil varning är under ökande nivåer av mental arbetsbelastning i en primär uppgift. I denna studie använde vi tre simulerade flyguppgiftsförhållanden där vi varierade den mentala arbetsbelastningen medan vi presenterade en på vibrotaktil varning. Generellt sett fann vi en minskning av den övergripande effekten av varningssignalen när den mentala belastningen ökade, men denna tendens avtog allt eftersom nivån på arbetsbelastningen steg. Detta indikerar att vibrotaktila varningssignaler kan användas för att förmedla information under ökande nivåer av primär mental arbetsbelastning (Rosa, Marsja, & K-Ljungberg, 2020).


### Tal i Brus och hörselnedsättning
På senare tid har jag utökat min forskning till att innefatta området kognitiv hörselvetenskap och handikappvetenskap. Tillsammans med nationella forskare har vi fokuserat på sambandet mellan kognitiv funktion, ålder och tal i brus. I en studie har vi använt avancerade statistiska metoder (exv. faktoranalys och strukturell ekvationsmodellering; SEM) med ett relativt stort stickprov för att undersöka hur kognitiv funktion och ålder påverkar prestation i tal-i-brus-test hos individer med och utan hörselnedsättning. Målet med denna studie var att med hjälp av multigrupp-SEM modellera sambandet mellan kognitiv funktion, åldrande, och identifikation av tal i brus. Denna studie utökar tidigare studier som framförallt undersökt dessa samband hos individer med hörselnedsättning, i mindre stickprov, och med mindre avancerade statistiska metoder (se exv. Dryden et al., 2017 för en översikt). Vi fann kognitiv funktion och ålder har liknande inverkan oavsett om individen har en hörselnedsättning eller inte (Marsja et al., 2022). Det vill säga, vi visade att för äldre individer är kognitiv förmåga minst lika viktig för att identifiera tal i brus och är i linje med Ease-of-Language Use-modellen (ELU; e.g., Rönnberg et al., 2021). Enligt ELU antas det att både en process- och lagringsfunktion krävs när det är ogynnsamma förhållanden, som exv. vid bakgrundsljud.

Detta resultat stämmer överens med vad vi funnit i en tidigare studie: hög arbetsminneskapacitet är relaterad till bättre prestanda vid taligenkänning i bakgrundsbrus för en grupp äldre och en grupp yngre personer med normal hörsel (Stenbäck, et al., 2021). I denna studie fann vi även att högre arbetsminneskapacitet var negativt relaterat till hur ansträngande det var att lyssna på tal i bakgrundsbrus. Det vill säga, högre arbetsminneskapacitet gör det lättare att lyssna (Stenbäck et al., 2021).

Arbetsminneskapacitet och kognitiv kontroll (inhibition) har vi även studerat i relation till bakgrundsljud som bär information eller inte (Stenbäck et al., Submitted). Vi fann att arbetsminnet är viktigare när bakgrundsbruset bär information (dvs. består av talljud) än när det inte består av information (dvs. består statiskt brus).  I en ytterligare studie, hade vi som mål att undersöka samband mellan självrapporterade hörselrelaterade mått (dvs. ett frågeformulär) och prestationsbaserade beteendemått (taligenkänning i brus; Stenbäck et al., Under Revision). Vi analyserade data från två tal-i-brustest som vanligen används i hörselkliniken (Hagerman och Hearing-In-Noise-Test; HINT). Dessa två tal-i-brustest skiljer sig i att meningarna i Hagerman saknar kontext medan meningarna i HINT har kontext. Denna studie visade att beteende- och självrapporteringsmått är relaterade till varandra hos äldre normalt hörande vuxna. Vi fann emellertid inte ett samband mellan dessa mätningar hos hörapparatanvändare, vilket belyser det tvetydiga sambandet mellan beteenden. och självrapporteringsåtgärder. Slutligen undersöker vi också hur logisk slutledning (både auditiv och visuell) kan vara relaterad till tal i brusigenkänning (Stenbäck, Marsja, Danielsson, & Rönnberg, In Preparation).


## Planerad forskning
I projekten nedan är det planerat att jag är forskningsledare om inte annat anges (dvs., om någon annan anges som PI är det inte jag som är projektansvarig).

### "Zoom Fatigue"
Tack vare min tidigare och nuvarande forskning är jag införstådd med att hörselnedsättning påverkar förmågan att bland annat kommunicera och etablera och upprätthålla sociala relationer. Tillsammans med forskare i funktionsnedsättning, pedagogik, och audiologi så planerar jag att undersöka hur hjälpmedel såsom textning av videosamtal kan påverka förståelse och lyssningsansträngning.
Generellt sett är lyssnande en automatisk och enkel process, särskilt under ideala förhållanden där inga explicita processer är engagerade (t.ex. Rönnberg et al., 2013). Men under ogynnsamma förhållanden (t.ex. när talsignalen är förvrängd) kan lyssnandet bli mer ansträngande (Rönnberg et al., 2013). Ogynnsamma förhållanden uppstår i både det sociala livet och arbetslivet. Till exempel, när man använder digitala medier där talsignalen alltid är förvrängd (t.ex. videosamtal och möten). Dessutom är lyssnande betydligt mer ansträngande för personer med hörselnedsättning (Kramer et al., 2006) och en stor del av Sveriges befolkning i arbetsför ålder (18,5 %) beräknas ha en hörselnedsättning (Hörselskadades riksförbund, 2017). 
Ogynnsamma lyssningsförhållanden kan också minska förståelsen och påverka minnet negativt (t.ex., för noveller; Piquado et al. 2012; Ward et al. 2016). Till exempel rapporterade Piquado med kollegor (2012) att lyssnare med hörselnedsättning visade sämre minne för noveller jämfört med normalhörande lyssnare. På grund av ökad lyssningsansträngning kan en individ med hörselnedsättning sluta använda hörapparater eller välja att inte delta i ett socialt evenemang (se Peelle, 2018). Dessutom, även vid deltagande, ökar ansträngande lyssnande stress och trötthet hos individer med hörselnedsättning (Hornsby, 2013) och ökar frånvaro och sjukdom på arbetsplatsen (t.ex. Nachtegaal, 2009). Flera faktorer angående hinder i arbetslivet har också identifierats för individer med HI, inklusive brist på arbetsplatsboende och brist på hjälpmedel (t.ex. Granberg & Gustafson, 2021). Det är därför av stor vikt när stora förändringar görs inom arbetsmiljön att stor noggrannhet iakttas för att möjliggöra anpassning och användning av hjälpmedel (t.ex. att använda textning i videomöten). Detta både för personer med hörselnedsättning såväl som normalt hörande.


#### Studie 1: Intervjuer med fokusgrupper (Finansierad)
En kvalitativ delstudie av detta projekt är redan finansierad av Hörselforskningsfonden (DNR: IBL-2021-00170) och har som mål att beskriva upplevelser, förståelse, och konsekvenser av digitalisering av arbetsliv. Vidare kommer resultatet från det finansierade projektet också att vara en utgångspunkt för vidare forskning om förutsättningarna för personer med hörselnedsättning i en digital värld samt en studie om hur man kan förbättra situationen. Detta både genom att vi får en rik bild, genom kvalitativ metod, och eftersom resultatet ämnas användas till att skapa ett instrument som kan användas att undersöka detta i även en kvantitativ kontext.


#### Studie 2 och 3: Förbättra digitala möten
I detta projekt planerar jag ytterligare två delstudier: en experimentell studie där vi vill undersöka proportionen av fel i en text (i relation till det talade ljudet) som krävs för att minska lyssningsansträngning och öka förståelse av det som sägs. Eftersom ljudkvalitet har funnits påverka både lyssningsansträngning och förståelse (se Mattys et al., 2012 för en översikt) samt att videosamtal medför föränderlig kvalitet så vill vi även undersöka detta i experimentet. I den andra studien planerar vi att följa upp experimentet med en enkätundersökning som baseras på de data från det mindre. Enkäten ska utformas baserat på de resultat vi erhåller i det projekt som redan är finansierat. Att använda oss av en kvalitativ ansats gör att vi att vi även fångar upp mer hälso- och arbetspsykologiska aspekter (exv. stress, deltagande i arbetslivet) av digitalisering samt hur textningens eventuella effekter. Slutligen för att ytterligare fånga andra aspekter såsom upplevelser och förståelse gällande lyssningsansträngning och förståelse, digitalisering, så ämnar vi att även följa upp med intervjuer. Således har den andra planerade studien en mixed-methods-ansats där vi integrerar kvalitativa data efter vi samlat in kvantitativt (dvs. med enkäten). Vi kommer därmed erhålla en bred bild av både positiva och negativa aspekter samt få ett resultat som vi anser får en högre ekologisk valididet. 

De två delstudierna (2 och 3), och det av Hörselforskningsfonden finansierat (Studie 1), bedrivs i samarbete med de Hörselskadades Riksförbund (HRF). Jag planerar att söka medel för studie 2 och 3 av projektet från bland annat FORTE och AFA försäkringar. Målet med det övergripande projektet är att undersöka hur digitaliseringen av arbete och det sociala live har påverkat individer med hörselnedsättning. Specifikt syftar vi till att 1) undersöka om textstöd i videomöten positivt påverkar förståelse och lyssnande, och 2) hur de positiva effekterna av att använda textstöd kommer att påverka delaktighet (både socialt och i arbetslivet). 

Samarbetspartners: 
    
  - Dr Victoria Stenbäck, Avdelningen för Pedagogik och Didaktik, Institutionen för Beteendevetenskap och Lärande, Linköpings Universitet
  - Dr Carine Signoret, Avdelningen för Handikappvetenskap, Institutionen för Beteendevetenskap och Lärande, Linköpings Universitet
  - Dr Ann-Charlotte Bivall, Avdelningen för Pedagogik och Sociologi, Institutionen för Beteendevetenskap och Lärande, Linköpings Universitet
  - Dr Antje Heinrich, Avdelningen för Mänsklig Kommunikation, Utveckling och Hörsel, Manchester Universitet


#### Ytterligare delstudier
Ovanstående projekt ämnas att utföras med en än mer experimentell än tillämpad ansats där vi endast fokuserar på experimentella manipulationer av textningen. Detta projekt ämnar bidra till teoretisk kunskap kring audiovisuellt processande hos individer med hörselnedsättning såväl som med andra funktionsnedsättningar men även normalt hörande individer. Detta projekt är än i sin linda men vi har identifierat lämpliga finansiärer som till exempel Vetenskapsrådet, Riksbankens Jubileumsfond.

Samarbetspartners: 

  - Dr Victoria Stenbäck, Avdelningen för Pedagogik och Didaktik, Institutionen för Beteendevetenskap och Lärande, Linköpings Universitet
  - Dr Carine Signoret, Avdelningen för Handikappvetenskap, Institutionen för Beteendevetenskap och Lärande, Linköpings Universitet
  

### Relationen mellan läs- och skrivvanor och psykosocial hälsa hos skolungdomar med hörselnedsättning
I detta projekt planerar vi att undersöka ungdomar med hörselnedsättning i årskurs 7–9 och om läs- och skrivvanor, motivation, betyg och stödundervisning samt psykosocial hälsa. Framgångsrik talspråksutveckling hos barn med hörselnedsättning är beroende av tidig upptäckt av hörselnedsättningen, tillgång till hörselhjälpmedel – till exempel hörapparat eller cochleaimplantat – och kontinuerlig intervention med syfte att främja användningen av talat språk (e.g., Yoshinaga-Itano et al., 2017). Trots medicinska, teknologiska och pedagogiska framsteg, medför emellertid en hörselnedsättning, oavsett svårighetsgrad eller typ, likväl en ökad risk för problem med det talade språket (Tomblin et al., 2015), och svårigheter med läsning och skrivning som kräver uppföljning och intervention under skolåren (Wang et al., 2019). Elever med hörselnedsättning ligger ofta efter jämnåriga med typisk hörsel gällande förmågor relaterade till språk, läsning och skrivning, till exempel talspråksförståelse, läsförståelse och förmågan att uttrycka sig i skrift (Sarant et al 2015). Elever med hörselnedsättning når inte läroplanens kunskapsmål i samma utsträckning som jämnåriga, och andelen som går vidare till högskolestudier är bara omkring 15 procent (SOU, 2016), jämfört med över 50 procent för elever med typisk hörsel (SCB, 2021). Hörselnedsättning ökar också risken att drabbas av psykosocial ohälsa (Theunissen et al., 2014). 

Målet med detta projekt är att öka kunskapen om hur, vad och varför ungdomar med hörselnedsättning läser och skriver. Det gäller till exempel hur mycket tid som tillbringas med att läsa och skriva och i vilka sammanhang det görs (hur), vilken typ av texter som läses (vad) och vad som motiverar till läsning och skrivning (varför). Ett annat mål är att ge en bild av vilket stöd ungdomar med hörselnedsättning får eller upplever sig behöva i skolan för att kunna delta på lika villkor i aktiviteter som inkluderar läsning och skrivning. Ytterligare ett mål är att få förståelse för hur läs- och skrivvanor hänger samman med hur eleverna mår och hur väl de uppnår kunskapsmålen i skolan. Projektet kommer att ge kunskap om vad som hindrar respektive underlättar framgångsrik och lustfylld läsning och skrivning. Med den kunskapen som grund kan sedan konkreta förslag ges på hur läsning och skrivning kan främjas i denna grupp.

Samarbetsparnters:

  - Dr Victoria Stenbäck (PI), Avdelningen för Pedagogik och Didaktik, Institutionen för Beteendevetenskap och Lärande, Linköpings Universitet
  - Dr Simon Sundström, Institutet för Specialpedagogik, Oslo Universitet


### Referenser

Cherry, E. C. (1953). Some experiments on The recognition of Speech, with one and with Two Ears. *The Journal of the Acoustical Society of America, 25*(5), 975–979.

Dryden, A., Allen, H. A., Henshaw, H., & Heinrich, A. (2017). The Association Between Cognitive Performance and Speech-in-Noise Perception for Adult Listeners: A Systematic Literature Review and Meta-Analysis. Trends in Hearing, 21, 1–21. https://doi.org/10.1177/2331216517744675

Granberg, S., & Gustafsson, J. (2021). Key findings about hearing loss in the working-life: a scoping review from a well-being perspective. *International Journal of Audiology, 60*(sup2), 60–70. https://doi.org/10.1080/14992027.2021.1881628

Hornsby, B. W. Y. (2013). The effects of hearing aid use on listening effort and mental fatigue associated with sustained speech processing demands. *Ear and Hearing, 34*(5), 523–534. https://doi.org/10.1097/AUD.0b013e31828003d8

Hörselskadades Riksförbund. (2017). Hörselskadade i siffror 2017. Stockholm.

Kramer, S. E., Kapteyn, T. S., & Houtgast, T. (2006). Occupational performance: Comparing normally-hearing and hearing-impaired employees using the Amsterdam Checklist for Hearing and Work. *International Journal of Audiology, 45*(9), 503–512. https://doi.org/10.1080/14992020600754583

Ljungberg, J. K., Parmentier, F. B. R., Jones, D. M., Marsja, E., & Neely, G. (2014). ‘What’s in a name?’ ‘No more than when it’s mine own’. Evidence from auditory oddball distraction. *Acta Psychologica, 150*, 161–166. https://doi.org/10.1016/j.actpsy.2014.05.009

Ljungberg, J. K., & Parmentier, F. B. R. (2012). Cross-modal distraction by deviance: Functional similarities between the auditory and tactile modalities. Experimental Psychology, 59(6), 355–363. https://doi.org/10.1027/1618-3169/a000164

Marsh, J. E., Vachon, F., Sörqvist, P., Marsja, E., Röer, J. P., and Ljungberg, J. K. (Manuscript in Preparation). Irrelevant vibro-tactile stimuli produce a changing-state effect: Implications for theories of interference in short-term memory.

Marsja, E., Neely, G., and Ljungberg, J. K. (2018). Investigating Deviance Distraction and the Impact of the Modality of the To-Be-Ignored Stimuli. *Experimental Psychology 65*. doi:10.1027/1618-3169/a000390.

Marsja, E. (2017). Attention capture by sudden and unexpected changes: a multisensory perspective (PhD thesis). Umeå University, Umeå. Retrieved from http://urn.kb.se/resolve?urn=urn:nbn:se:umu:diva-141852

Marsja, E., Marsh, J. E., Hansson, P., & Neely, G. (2019). Examining the Role of Spatial Changes in Bimodal and Uni-Modal To-Be-Ignored Stimuli and How They Affect Short-Term Memory Processes. *Frontiers in Psychology*, 10. https://doi.org/10.3389/fpsyg.2019.00299

Marsja, E., Neely, G., and Ljungberg, J. K. (In Preparation). Deviance distraction in the auditory and tactile modalities after repeated exposure: differential aspects of tactile and auditory deviants.

Marsja, E., Stenbäck, V., Moradi, S., Danielsson, H., & Rönnberg, J. (Accepted). Is Having Hearing Loss Fundamentally different? Multi-group structural equation modeling of the effect of cognitive functioning on speech identification. *Ear and Hearing*.

Mattys, S. L., Davis, M. H., Bradlow, A. R., & Scott, S. K. (2012). Speech recognition in adverse conditions: A review. *Language and Cognitive Processes, 27*(7–8), 953–978. https://doi.org/10.1080/01690965.2012.705006

Nachtegaal, J., Kuik, D. J., Anema, J. R., Goverts, S. T., Festen, J. M., & Kramer, S. E. (2009). Hearing status, need for recovery after work, and psychosocial work characteristics: Results from an internet-based national survey on hearing. *International Journal of Audiology, 48*(10), 684–691. https://doi.org/10.1080/14992020902962421

Peelle, J. E. (2018). Listening effort: How the cognitive consequences of acoustic challenge are reflected in brain and behavior. *Ear and Hearing, 39*(2), 204–214. https://doi.org/10.1097/AUD.0000000000000494

Piquado, T., Benichov, J. I., Brownell, H., & Wingfield, A. (2012). The hidden effect of hearing acuity on speech recall, and compensatory effects of self-paced listening. *International Journal of Audiology, 51*(8), 576–583. https://doi.org/10.3109/14992027.2012.684403

Rosa, E., Marsja, E., & Ljungberg, J. K. (2020). Exploring Residual Capacity: The Effectiveness of a Vibrotactile Warning During Increasing Levels of Mental Workload in Simulated Flight Tasks. *Aviation Psychology and Applied Human Factors, 10*(1), 13–23. https://doi.org//10.1027/2192-0923/a000180

Rönnberg, J., Lunner, T., Zekveld, A., Sörqvist, P., Danielsson, H., Lyxell, B., Dahlström, Ö., Signoret, C., Stenfelt, S., Pichora-Fuller, M. K., & Rudner, M. (2013). The Ease of Language Understanding (ELU) model: theoretical, empirical, and clinical advances. *Frontiers in Systems Neuroscience, 7*(JUNE), 1–17. https://doi.org/10.3389/fnsys.2013.00031

Sarant, J. Z., Harris, D. C., & Bennet, L. A. (2015). Academic outcomes for school-aged children with severe--profound hearing loss and early unilateral and bilateral cochlear implants. *Journal of Speech, Language, and Hearing Research, 58*(3), 1017–1032.

SCB. 2021. Övergång gymnasieskola – eftergymnasial utbildning, examinerade från gymnasieskolan 

SOU 2016:46. 2016. Samordning, ansvar och kommunikation – vägen till ökad kvalitet i utbildningen för elever med vissa funktionsnedsättningar. Utbildningsdepartementet.

Stenbäck, V., Marsja, E., Hällgren, M., Lyxell, B., & Larsby, B. (2021). The Contribution of Age, Working Memory Capacity, and Inhibitory Control on Speech Recognition in Noise in Young and Older Adult Listeners. *Journal of Speech, Language, and Hearing Research, 64*(11), 4513–4523. https://doi.org/10.1044/2021_JSLHR-20-00251

Stenbäck, V., Marsja, E., Hällgren, M., Lyxell, B., & Larsby, B. (Submitted). Informational masking and listening effort in speech-recognition-in-noise – the role of working memory capacity and inhibitory control in older adults with and without hearing impairment.

Stenbäck, V., Marsja, E., Ellis, R., & Rönnberg, J. (Submitted). Relationships between objective and subjective outcome measures of speech recognition in noise.

Theunissen, S. C. P. M., Rieffe, C., Kouwenberg, M., De Raeve, L. J. I., Soede, W., Briaire, J. J., & Frijns, J. H. M. (2014). *Behavioral problems in school-aged hearing-impaired children: the influence of sociodemographic, linguistic, and medical factors. European Child & Adolescent Psychiatry, 23*(4), 187–196.

Tomblin, J. B., Harrison, M., Ambrose, S. E., Walker, E. A., Oleson, J. J., & Moeller, M. P. (2015). Language Outcomes in Young Children with Mild to Severe Hearing Loss. *Ear & Hearing, 36*(Supplement 1), 76S-91S. https://doi.org/10.1097/AUD.0000000000000219

Wang, J., Quach, J., Sung, V., Carew, P., Edwards, B., Grobler, A., Gold, L., & Wake, M. (2019). Academic, behavioural and quality of life outcomes of slight to mild hearing loss in late childhood: a population-based study. *Archives of Disease in Childhood, 104*(11), 1056–1063.

Ward, C. M., Rogers, C. S., Van Engen, K. J., & Peelle, J. E. (2016). Effects of Age, Acoustic Challenge, and Verbal Working Memory on Recall of Narrative Speech. *Experimental Aging Research, 42*(1), 97–111. https://doi.org/10.1080/0361073X.2016.1108785

Yoshinaga-Itano, C., Sedey, A. L., Wiggin, M., & Chung, W. (2017). Early Hearing Detection and Vocabulary of Children With Hearing Loss. *Pediatrics, 14*0(2). https://doi.org/10.1542/peds.2016-2964