---
title: "Pedagogisk Reflektion"
author: "Erik Marsja"
address: Tvistevägen 26, SE-907 36 Umeå, Sweden
dob: 19810526
email: erik.marsja@liu.se
web: www.marsja.se
phone: +4670-3633662
github: marsja
output:
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
    keep_tex: no
geometry: margin=1in
subparagraph: yes
fontawesome: yes
swedish: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Under mina år som lärare på högskolenivå har jag skaffat mig erfarenhet av undervisning och gått kurser i högskolepedagogik. Detta har haft en stark inverkan på min utveckling som lärare och jag reflekterar ofta över min roll som lärare samt drivs av att utveckla och förbättra mina pedagogiska färdigheter. Som ett resultat av detta lägger jag ofta mycket tid på att förbereda min undervisning.

\
Min kunskapssyn utgår från de ämnen jag läst under min tid som grund- och forskarstuderande; kognitionsvetenskap (i synnerhet kognitiv psykologi). Det vill säga, min uppfattning är att kunskap bygger på empiriska resultat (Gustafsson, 2002). Min uppfattning har dock ändrats till att anse att djupare kunskap också kräver förståelse för fakta. Denna utveckling har sprungit från min erfarenhet av undervisning, och de pedagogiska kurser jag läser, men också min specialisering i psykologi som ämne. Jag har kommit att anta ett förhållningssätt baserat på bland annat Gustafssons (2002) fyra F (fakta, förståelse, förtrogenhet, och färdighet). Vidare har jag, under min tid som postdoktor i handikappvetenskap, även kommit att undervisa såväl om som för individer med funktionsnedsättningar. Detta har lett till ytterligare reflektioner kring min pedagogik.

Eftersom merparten av min undervisning har bedrivits i början av studenterna utbildning har mitt mål varit att få studenter att lära sig förstå fakta (dvs. grundvetenskap). Jag har dock även haft möjlighet att undervisa i kurser med tillämpad inriktning, och projektkurser där studenter ska kunna tillämpa grundläggande naturvetenskap i direkt kontakt med näringslivet. Här har utmaningen varit att stödja studenter att tillämpa sina teoretiska kunskaper men också att få dem att teoretiskt förstå de praktiska aspekterna av sitt arbete.

För mig är lärande en dynamisk process som varar en livstid och handlar om att få fram fakta, förståelse, förtrogenhet och skicklighet (eller bara fakta och förståelse i många fall i de ämnen jag undervisar i). Lärande är för mig väldigt starkt kopplat till den psykologiska konstruktion som vi kallar minne (dvs. den process som gör att vi kan lagra och komma ihåg information) men också till beteende. Med det sagt, anser jag också att lärande kräver ett sunt kritiskt tänkande där bland annat kunskap om vikten av källkritik gör att studenterna införlivar ny kunskap med tidigare erfarenheter. På sikt kan denna förhoppningsvis bidra till att studenterna kan omsätta de nya kunskaperna i praktiken.

Undervisningen har självklart en central roll i lärandet och huvudsyftet med all utbildning är att studenterna ska nå förväntade mål. Det vill säga att undervisning är en målinriktad verksamhet som syftar till att främja studenters lärande. För att uppnå detta behöver man skapa en bra miljö för studenter. En bra lärmiljö vilar till stor del på min pedagogiska kompetens. Jag anser att mitt uppdrag inte bara är att förmedla kunskap utan jag behöver också skapa en intressant miljö som stimulerar studenters lärande. I denna miljö är engagemang och entusiasm är väldigt viktigt eftersom, enligt min erfarenhet, mitt engagemang mer eller mindre speglas i studenterna.

En annan viktig faktor är att skapa en öppen atmosfär där studenter vågar ställa frågor. Här är vikten av genus och intersektionellt perspektiv avgörande. Förutom att sträva efter att införliva dessa perspektiv i undervisningen, vilket i många av de undervisningsmoment jag haft inte alltid är möjligt, innebär detta också att försöka uppmärksamma och motverka negativa tendenser relaterade till kön, sexualitet, etnicitet, funktionsnedsättning och ålder i alla undervisningssammanhang. Jag tror också att det är av stor vikt att arbeta med medvetenhet om dessa perspektiv även i själva planeringsstadiet (till exempel aktuellt studiematerial, gruppövningar, handledning).

Jag har genom åren skaffat mig erfarenhet av att undervisa i flera former såsom föreläsningar, handledning av till exempel examensarbeten (på avancerad och grundnivå), ansvara för seminarier och gruppövningar, laborationer och workshops. Som framgår av den bifogade tabellen har min undervisning vid universitetet skett på både grundnivå och avancerad nivå. Min undervisning har skett för studenter inom handikappvetenskap, pedagogik, psykologi, tränarprogrammet och kognitionsvetarprogrammet, olika lärarprogram, studenter på fristående kurser, internationella studenter (på engelska), samt civilingenjörer. Jag upplever denna mångfald av studentgrupper som berikande i tvärvetenskaplig respekt. Eftersom jag har haft en bredd i mina undervisningsuppdrag har jag även erfarenhet av en rad olika examinationsformer såsom seminarier, muntliga såväl skriftliga tentamen (även hem- och salstentor), och skriftliga uppgifter (exv. korta granskningar av kvalitativ forskning). Inom ramen som handledare för kandidatuppsatser i kognitionsvetenskap har jag, slutligen, även examinerat uppsatser. 

Något som är viktigt för mig är att min undervisning förbättras och utvecklas. Detta sker i takt med att jag lär mig nya pedagogiska färdigheter och teorier men också när jag upptäcker att studenter verkar ha svårt med vissa aspekter. Till exempel, när jag började föreläsa i perception för snart 8 år sedan. Jag höll den första föreläsningen för studenter på träningsprogrammet. Min första tanke var: i deras framtida yrkesroll, hur kan kunskap om mänsklig perception vara användbar? Här försökte jag med en rad olika exempel från sporter att förmedla att kunskap om perception skulle kunna förbättra bland annat idrottarens prestation.

Att införliva pedagogisk teori är viktigt. Till exempel har jag praktiskt tillämpat aspekter av variationsteori (se Ling & Marton, 2012). Vanligtvis ställer jag olika teoretiska åsikter eller förhållningssätt mot varandra så att det blir lättare för studenter att lära sig dem. Genom att låta studenter bryta ner olika, ibland väldigt lika, teorier och se vad som skiljer dem åt upplever jag att det förenklar deras förståelse.

I en kurs i handikappvetenskap har jag till exempel tillämpat de 4 F:en. För att uppnå förtrogenhet och färdighet, är jag övertygad att jag som lärare måste arbeta på ett sätt så att fakta kan tillämpas och på så sätt kan studenten förstå vad den har lärt mig. I dessa kurser har jag använt mig av enklare datorlabbar i statistik med mjukvaran Jamovi, där jag först gick igenom teori och sedan fick studenter själva arbeta med det ett material (svara på statistikfrågor). I den här kursen har jag även arbetat med examinationer där studenter får tillämpa sina kunskaper och förståelse för statistik genom att arbeta med material och hitta rätt analysmetod för att sedan utföra statistiska analyser. Vid mina 3 år vid Linköpings Universitet har jag även gått en kurs i problembaserat lärande och handlett basgrupper vid olika terminer av psykologprogrammet. Här är det centralt, anser jag, att stimulera studenternas självständighet och lärande genom att ställa relevanta frågor. I problembaserat lärande är det också en utmaning att examinera studenterna eftersom jag måste stimulera deras lärande och aktivitet.

\
Avslutningsvis vill jag förmedla att min utveckling som universitetslärare naturligtvis innebär att lära sig om, och anamma, fler pedagogiska teorier och försöka koppla dessa till psykologiska teorier om undervisning och lärande. Det som är mest uppenbart är mer individualistiska synsätt som relationspedagogik (Aspelin, 2011) och hur jag har fått användning av dessa. Eftersom en stor del av min undervisning har varit handledning har jag försökt nå studenterna genom att skapa en relation och utifrån denna relation ha interaktion och samarbete. Jag tror att detta är väldigt viktigt eftersom jag ofta undervisar för studenter med olika bakgrund samt slutmål. Det innebär att jag i min handledning strävar efter att anpassa mig till grupperna och individerna i grupperna. Här kommer kunskap om relationspedagogik väl till pass liksom mina kunskaper samt erfarenhet av problembaserat lärande.

 
## Referenser

Aspelin, J. (2011). Vad är relationell pedagogik? Persson S. (Ed.), *Om relationell pedagogik* (pp. 13-25). Malmö: Gleerups Utbildning AB

Gustavsson, B. (2002). Vad är kunskap? En diskussion om praktisk och teoretisk kunskap. Kalmar: Leanders Grafiska AB.

Ling, L. M., & Marton, F. (2012). Towards a science of the art of teaching: Using variation theory as a guiding principle of pedagogical design. International Journal for Lesson and Learning Studies, 1(1), 7–22. http://doi.org/10.1108/20468251211179678
